version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: "registry.name/${$DOCKER_USERNAME}/reverseprogxy"
  backend_user:
    build:
      context: ./udagram-api-user
    image: "registry.name/${$DOCKER_USERNAME}/udagram-api-user"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_DB=HAMDA
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: "registry.name/${$DOCKER_USERNAME}/udagram-api-feed"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_DB=HAMDA
  frontend:
    build:
      context: ./udagram-frontend
    image: "registry.name/${$DOCKER_USERNAME}/udagram-frontend:local"

